hpc-maths/samurai

- include/samurai/petsc/petsc_assembly.hpp
- include/samurai/petsc/petsc_cell_based_scheme_assembly.hpp
- include/samurai/petsc/petsc_diffusion_FV_star_stencil.hpp
- include/samurai/petsc/petsc_diffusion_solver.hpp
The Dirichlet unknowns were eliminated. Now the user can choose between if elimination or not.
> New way of Dirichlet enforcement

- .github/workflows/conan.yml
- demos/FiniteVolume/AMR_Burgers_Hat.cpp
- demos/FiniteVolume/BZ/bz_2d_AMR.cpp
- demos/FiniteVolume/advection_1d.cpp
- demos/FiniteVolume/advection_2d.cpp
- demos/FiniteVolume/level_set.cpp
- demos/FiniteVolume/level_set_from_scratch.cpp
- demos/FiniteVolume/scalar_burgers_2d.cpp
- demos/LBM/D2Q4444_Euler_Lax_Liu_uniform.cpp
- demos/LBM/test_D1Q2.cpp
- demos/tutorial/AMR_1D_Burgers/step_2/update_sol.hpp
- demos/tutorial/AMR_1D_Burgers/step_3/update_sol.hpp
- demos/tutorial/AMR_1D_Burgers/step_4/AMR_criterion.hpp
- demos/tutorial/AMR_1D_Burgers/step_6/update_sol.hpp
- demos/tutorial/reconstruction_1d.cpp
- demos/tutorial/reconstruction_2d.cpp
- demos/tutorial/reconstruction_3d.cpp
- doc/source/tutorial/field.rst
- include/samurai/algorithm.hpp
- include/samurai/boundary.hpp
- include/samurai/cell.hpp
- include/samurai/mesh_interval.hpp
- include/samurai/operators_base.hpp
- include/samurai/stencil.hpp
- function cell_length(level)
- argument h removed from for_each_level
- optional boolean argument include_empty_levels
> for_each_level

- demos/FiniteVolume/CMakeLists.txt
- demos/FiniteVolume/heat_1d.cpp
- demos/multigrid/main.cpp
- include/samurai/indices.hpp
- include/samurai/petsc/petsc_assembly.hpp
- include/samurai/petsc/petsc_backward_euler.hpp
- include/samurai/petsc/petsc_cell_based_scheme_assembly.hpp
- include/samurai/petsc/petsc_diffusion_FV_star_stencil.hpp
- include/samurai/petsc/petsc_solver.hpp
- include/samurai/stencil.hpp
- Heat equation in backward Euler
- Class PetscDiffusionSolver renamed in PetscSolver
- Function for_each_cell_having_children (resp. having_parent) renamed in for_each_projection_ghost (resp. prediction_ghost)
> Heat equation in backward Euler

- .github/workflows/conan.yml
- demos/FiniteVolume/CMakeLists.txt
- demos/FiniteVolume/heat_1d.cpp
- demos/FiniteVolume/stokes_2d.cpp
- demos/multigrid/main.cpp
- include/samurai/indices.hpp
- include/samurai/petsc.hpp
- include/samurai/petsc/backward_euler.hpp
- include/samurai/petsc/block_assembly.hpp
- include/samurai/petsc/cell_based_scheme.hpp
- include/samurai/petsc/diffusion_FV.hpp
- include/samurai/petsc/matrix_assembly.hpp
- include/samurai/petsc/petsc_assembly.hpp
- include/samurai/petsc/petsc_backward_euler.hpp
- include/samurai/petsc/petsc_block_assembly.hpp
- include/samurai/petsc/petsc_cell_based_scheme_assembly.hpp
- include/samurai/petsc/petsc_diffusion_FV_star_stencil.hpp
- include/samurai/petsc/petsc_solver.hpp
- include/samurai/petsc/solver.hpp
- include/samurai/petsc/utils.hpp
- include/samurai/petsc/zero_operator.hpp
- include/samurai/petsc/zero_operator_FV.hpp
- include/samurai/stencil.hpp
- include/samurai/utils.hpp
Nested PETSc matrices can be built using a list of schemes.
Stokes example is implemented.
> Block matrices

- include/samurai/bc.hpp
This is the first PR to solve the bc. Other issues probably remain when we try to find diagonal ghosts for the successive layers.
Furthermore, when we have periodic conditions, the relevant directions must be removed from the directions vector on each boundary for a given field.
> fix: bc when ghost_width > 1

- demos/FiniteVolume/heat_1d.cpp
- demos/FiniteVolume/stokes_2d.cpp
- include/samurai/interval.hpp
- include/samurai/petsc/block_assembly.hpp
- include/samurai/petsc/cell_based_scheme.hpp
- include/samurai/petsc/flux_based_scheme.hpp
- include/samurai/petsc/fv/FV_scheme.hpp
- include/samurai/petsc/fv/diffusion_FV.hpp
- include/samurai/petsc/fv/divergence_FV.hpp
- include/samurai/petsc/fv/gradient_FV.hpp
- include/samurai/petsc/fv/zero_operator_FV.hpp
- include/samurai/petsc/matrix_assembly.hpp
- include/samurai/petsc/scheme_operators.hpp
- include/samurai/petsc/solver.hpp
- include/samurai/utils.hpp
- fix monolithic assembly
- operator and solver assignment operators
- fix memory management
- fix warnings
> fix: monolithic Stokes assembly

- include/samurai/interface.hpp
- include/samurai/numeric/gauss_legendre.hpp
- include/samurai/petsc/block_assembly.hpp
- include/samurai/petsc/fv/FV_scheme_assembly.hpp
- include/samurai/petsc/fv/flux_based_scheme_assembly.hpp
- include/samurai/schemes/fv/explicit_flux_based_scheme.hpp
- include/samurai/schemes/fv/flux_based_scheme.hpp
- include/samurai/schemes/fv/operators/diffusion_FV.hpp
- include/samurai/schemes/fv/operators/divergence_FV.hpp
- include/samurai/schemes/fv/operators/gradient_FV.hpp
- include/samurai/schemes/fv/operators/identity_FV.hpp
- include/samurai/schemes/fv/scheme_operators.hpp
- Fix heat_1D demo
- Possibility to eliminate the ghosts from the linear sytem
> fix: heat + ghost elimination

- demos/FiniteVolume/level_set_from_scratch.cpp
- demos/FiniteVolume/stokes_2d.cpp
- demos/highorder/main.cpp
- demos/multigrid/test_cases.hpp
- demos/p4est/simple_2d.cpp
- demos/pablo/bubble_2d.cpp
- demos/tutorial/AMR_1D_Burgers/step_4/update_field.hpp
- demos/tutorial/AMR_1D_Burgers/step_4/update_mesh.hpp
- demos/tutorial/graduation_case_3.cpp
- include/samurai/algorithm.hpp
- include/samurai/algorithm/update.hpp
- include/samurai/bc.hpp
- include/samurai/cell.hpp
- include/samurai/cell_array.hpp
- include/samurai/field.hpp
- include/samurai/field_expression.hpp
- include/samurai/graduation.hpp
- include/samurai/interface.hpp
- include/samurai/io/from_geometry.hpp
- include/samurai/level_cell_array.hpp
- include/samurai/level_cell_list.hpp
- include/samurai/mesh.hpp
- include/samurai/numeric/gauss_legendre.hpp
- include/samurai/petsc/fv/FV_scheme_assembly.hpp
- include/samurai/stencil.hpp
- test/test_cell.cpp
- modify template parameter of a Cell
- add the cell inside the domain in the method which computes the values in FunctionBC
> feat: add cell_in in functionBC

- include/samurai/schemes/fv/flux_based/flux_based_scheme__nonlin.hpp
Fix non-linear schemes for scalar fields
> fix: non-linear schemes for scalar fields

- docs/source/_static/css/custom.css
- docs/source/conf.py
- docs/source/reference/finite_volume_schemes.rst
- docs/source/reference/index.rst
- docs/source/reference/local_schemes.rst
- docs/source/tutorial/index.rst
- docs/source/tutorial/reaction_diffusion.rst
Doc for the finite volume schemes and tutorial on the Nagumo equation
> docs: doc for the finite volume schemes and tutorial on the Nagumo equation

- demos/FiniteVolume/nagumo.cpp
- docs/source/reference/finite_volume_schemes.rst
- docs/source/reference/local_schemes.rst
- docs/source/tutorial/reaction_diffusion.rst
- include/samurai/petsc.hpp
- include/samurai/petsc/fv/cell_based_scheme_assembly.hpp
- include/samurai/petsc/linear_block_solver.hpp
- include/samurai/petsc/linear_solver.hpp
- include/samurai/petsc/nonlinear_local_solvers.hpp
- include/samurai/petsc/nonlinear_solver.hpp
- include/samurai/petsc/solver.hpp
- include/samurai/petsc/solver_helpers.hpp
- include/samurai/petsc/utils.hpp
- include/samurai/schemes/fv/FV_scheme.hpp
- include/samurai/schemes/fv/cell_based/algebraic_operators.hpp
- include/samurai/schemes/fv/cell_based/cell_based_scheme__nonlin.hpp
- include/samurai/schemes/fv/cell_based/cell_based_scheme_definition.hpp
- include/samurai/schemes/fv/cell_based/local_field.hpp
- include/samurai/schemes/fv/flux_based/algebraic_operators.hpp
- include/samurai/schemes/fv/flux_based/flux_definition.hpp
- include/samurai/schemes/fv/scheme_operators.hpp
- include/samurai/schemes/fv/utils.hpp
Non-linear CellBasedSchemes that have a stencil size of 1 are now solved by independent local Newton solvers instead of a global one.
Nagumo demo.
> feat: local newton solvers

- .github/workflows/ci.yml
- CMakeLists.txt
- update project_options to v0.33.0
- add clang version 15 in Linux CI
- specify target_properties for samurai
> chore: Add compiler

- demos/FiniteVolume/heat.cpp
- demos/FiniteVolume/heat_heterogeneous.cpp
- demos/FiniteVolume/linear_convection.cpp
- demos/FiniteVolume/nagumo.cpp
- demos/FiniteVolume/stokes_2d.cpp
- demos/highorder/main.cpp
- demos/multigrid/main.cpp
- include/samurai/petsc/fv/FV_scheme_assembly.hpp
- include/samurai/petsc/linear_block_solver.hpp
- include/samurai/petsc/linear_solver.hpp
- include/samurai/petsc/nonlinear_local_solvers.hpp
- include/samurai/petsc/nonlinear_solver.hpp
> chore: fix cppcheck errors

- include/samurai/algorithm/update.hpp
- include/samurai/mr/operators.hpp
- include/samurai/operators_base.hpp
- include/samurai/stencil.hpp
> chore: fix warning

- demos/FiniteVolume/advection_2d_user_bc.cpp
Fix stencil in advection_2d_user_bc
Demo wasn't working.
> fix: Fix advection_2d_user_bc

- include/samurai/mr/mesh.hpp
Add projection ghosts under the cells only if level_min != level_max.
> perf: Add MR ghosts only if level_min != level_max

- include/samurai/petsc/block_assembly.hpp
`reset()` is called in `create_matrix()` to compute all the block sizes.
In nested matrices, the sizes of 0-blocks were not computed.
> fix: fix block sizes for nested matrices

- include/samurai/mr/mesh.hpp
This PR fixes an issue that occurs when using periodic conditions. Some cells are identified as prediction cells, but they should be computed using a projection operation because they have cells above them at finer levels.
> fix: projection cells for periodic case

- include/samurai/indices.hpp
- include/samurai/mr/operators.hpp
- include/samurai/stencil.hpp
Fix warnings, except the `#pragma omp`
> chore: fix warnings for linux gcc

- docs/source/conf.py
The current version of samurai wasn't set correctly in the sphinx documentation. This PR fixes that.
> docs: fix samurai version in the documentation

- .github/workflows/ci.yml
- conda/mpi-environment.yml
The installation of PETSc in the context of MPI is broken. This PR fixes this issue.
> chore: fix MPI in the CI

- .github/workflows/ci.yml
- demos/FiniteVolume/burgers.cpp
- include/samurai/algorithm/graduation.hpp
- include/samurai/algorithm/update.hpp
- include/samurai/arguments.hpp
- include/samurai/boundary.hpp
- include/samurai/interface.hpp
- include/samurai/level_cell_array.hpp
- include/samurai/mesh.hpp
- include/samurai/mr/adapt.hpp
- include/samurai/mr/mesh.hpp
- include/samurai/samurai.hpp
- include/samurai/schemes/fv/flux_based/flux_based_scheme__lin_het.hpp
- include/samurai/schemes/fv/flux_based/flux_based_scheme__lin_hom.hpp
- include/samurai/schemes/fv/flux_based/flux_based_scheme__nonlin.hpp
- include/samurai/static_algorithm.hpp
- python/compare.py
This PR adds parallelism to the finite volume schemes with an explicit formulation. The periodic conditions have not yet been properly addressed and will be fixed in a future PR.
The Burgers_2D test case has been checked for various numbers of processes (see ci.yml).
> feat: parallel flux

- include/samurai/mr/adapt.hpp
add `update_ghost_mr(other_fields...)` in `harten` function
> fix: fix MRAdaptation with fields to adapt

- demos/multigrid/main.cpp
- include/samurai/boundary.hpp
- include/samurai/interface.hpp
- include/samurai/petsc/fv/FV_scheme_assembly.hpp
- include/samurai/schemes/fv/FV_scheme.hpp
- include/samurai/schemes/fv/operators/diffusion.hpp
- include/samurai/schemes/fv/operators/diffusion_old.hpp
Performance improvement in `for_each_interface` in the periodic case and some refactoring to prepare the development of periodic BC in implicit.
> perf: some performance improvement in for_each_interface

- demos/FiniteVolume/AMR_Burgers_Hat.cpp
- demos/FiniteVolume/advection_1d.cpp
- demos/FiniteVolume/advection_2d.cpp
- demos/FiniteVolume/advection_2d_user_bc.cpp
- demos/FiniteVolume/burgers.cpp
- demos/FiniteVolume/burgers_mra.cpp
- demos/FiniteVolume/burgers_os.cpp
- demos/FiniteVolume/level_set.cpp
- demos/FiniteVolume/level_set_from_scratch.cpp
- demos/FiniteVolume/lid_driven_cavity.cpp
- demos/FiniteVolume/linear_convection.cpp
- demos/FiniteVolume/linear_convection_obstacle.cpp
- demos/FiniteVolume/scalar_burgers_2d.cpp
Previously, the first save was not performed.
advection-2d
> fix: save issue in demos
