hpc-maths/samurai

- include/samurai/boundary.hpp
- include/samurai/indices.hpp
- include/samurai/petsc/petsc_cell_based_scheme_assembly.hpp
- include/samurai/stencil.hpp
The functions returning only cell indices are removed. The ones returning cells are used instead.
> Remove index functions

- demos/FiniteVolume/level_set_from_scratch.cpp
- demos/pablo/bubble_2d.cpp
- demos/tutorial/AMR_1D_Burgers/step_4/update_field.hpp
- include/samurai/algorithm/update.hpp
- include/samurai/field.hpp
- include/samurai/io/from_geometry.hpp
- include/samurai/mesh_holder.hpp
- include/samurai/mr/adapt.hpp
- include/samurai/mr/operators.hpp
- include/samurai/petsc/fv/FV_scheme_assembly.hpp
- include/samurai/utils.hpp
- test/test_field.cpp
- test/test_utils.cpp
Field_tuple is used in the multiresolution process in order to compute the details from several fields.
Now, we can make 
```
auto MRadaptation = samurai::make_MRAdapt(u, v);
```
And the details will be computed using the two fields `u` and `v`.
> feat: add Field_tuple

- demos/FiniteVolume/CMakeLists.txt
- demos/FiniteVolume/heat.cpp
The heat equation in N dimensions
> feat: heat N-D

- include/samurai/bc.hpp
The coordinates sent to the user-defined boundary functions are now located on the boundary.
> fix: BC function receives boundary coordinates

- demos/FiniteVolume/burgers.cpp
- demos/FiniteVolume/heat.cpp
- demos/FiniteVolume/stokes_2d.cpp
- demos/highorder/main.cpp
- demos/multigrid/main.cpp
- include/samurai/petsc/block_assembly.hpp
- include/samurai/petsc/fv/FV_scheme_assembly.hpp
- include/samurai/petsc/fv/scheme_operators_assembly.hpp
- include/samurai/petsc/solver.hpp
- include/samurai/schemes/fv/FV_scheme.hpp
- include/samurai/schemes/fv/cell_based_scheme.hpp
- include/samurai/schemes/fv/flux_based_scheme__lin_hom.hpp
- include/samurai/schemes/fv/flux_based_scheme__nonlin.hpp
- include/samurai/schemes/fv/operators/convection_FV__nonlin.hpp
- include/samurai/schemes/fv/operators/diffusion_FV.hpp
- include/samurai/schemes/fv/operators/divergence_FV.hpp
- include/samurai/schemes/fv/operators/divergence_FV__nonlin.hpp
- include/samurai/schemes/fv/operators/gradient_FV.hpp
- include/samurai/schemes/fv/operators/identity_FV.hpp
- include/samurai/schemes/fv/operators/zero_operator_FV.hpp
- include/samurai/schemes/fv/scheme_operators.hpp
Field object removed from the operators. Now only the field type is used.
> feat: remove field object from operators

- demos/FiniteVolume/CMakeLists.txt
- demos/FiniteVolume/heat_heterogeneous.cpp
- demos/FiniteVolume/lid_driven_cavity.cpp
- demos/FiniteVolume/stokes_2d.cpp
- demos/multigrid/main.cpp
- include/samurai/petsc/fv/flux_based_scheme_assembly.hpp
- include/samurai/schemes/fv/explicit_flux_based_scheme.hpp
- include/samurai/schemes/fv/flux_based_scheme__lin_het.hpp
- include/samurai/schemes/fv/flux_definition.hpp
- include/samurai/schemes/fv/operators/convection_FV__lin.hpp
- include/samurai/schemes/fv/operators/diffusion_FV.hpp
- include/samurai/schemes/fv/scheme_operators.hpp
Framework to define linear and heterogeneous fluxes.
Implemented examples:
- Heterogeneous diffusion
- Heterogeneous convection (used in the lid-driven cavity code).
> feat: linear heterogeneous fluxes

- include/samurai/mr/adapt.hpp
- include/samurai/mr/operators.hpp
- tests/CMakeLists.txt
- tests/test_adapt.cpp
This PR fixes the detail computation in the multi resolution process when several fields are used with different size.
see tests/test_adapt.cpp
> fix: detail computation in MRAdapt

- include/samurai/petsc/fv/FV_scheme_assembly.hpp
- include/samurai/petsc/nonlinear_solver.hpp
- include/samurai/schemes/fv/cell_based/local_field.hpp
- include/samurai/schemes/fv/scheme_operators.hpp
Fix problems that prevented the implementation of a high-order scheme in time:
- an algebraic operators between schemes has been added
- bugs in the global Newton solver have been fixed.
Time scheme of order 2 in Nagumo.
> fix: Fix operators for time integration

- include/samurai/schemes/fv/cell_based/cell_based_scheme_definition.hpp
- include/samurai/schemes/fv/utils.hpp
Using cell array instead of cell xtensor for the stencil of non-linear cell-based schemes.
Compilation issue when making a non-local cell-based scheme with a stencil.
Tested in Nicolas Grenier's level-set code.
> fix: cell array instead of cell xtensor for the stencil of non-linear cell-based schemes

- demos/FiniteVolume/linear_convection.cpp
- include/samurai/interface.hpp
When computing the flux on the boundary in the opposite direction, the stencil was wrong.
The 'flip(stencil)' instruction is replaced with 'stencil - direction'.
The flux-based schemes didn't work when the stencil was unsymmetric.
It was tested on the Lax-Wendroff scheme in N. Grenier's code.
> fix: Fix flux-based schemes with unsymmetric stencil

- .github/workflows/ci.yml
- docs/source/reference/finite_volume_schemes.rst
- include/samurai/schemes/fv/flux_based/algebraic_operators.hpp
- include/samurai/schemes/fv/flux_based/flux_based_scheme__lin_het.hpp
- include/samurai/schemes/fv/flux_based/flux_based_scheme__lin_hom.hpp
- include/samurai/schemes/fv/flux_based/flux_based_scheme__nonlin.hpp
- include/samurai/schemes/fv/flux_based/flux_definition.hpp
- include/samurai/schemes/fv/operators/convection_FV__lin.hpp
- include/samurai/schemes/fv/operators/convection_FV__nonlin.hpp
- include/samurai/schemes/fv/operators/diffusion_FV.hpp
- include/samurai/schemes/fv/operators/divergence_FV.hpp
- include/samurai/schemes/fv/operators/gradient_FV.hpp
Member 'flux_function' is renamed as 'cons_flux_function', expressing that the flux is conservative.
A new member 'flux_function' for non-conservative fluxes has been added. This function takes the same arguments, but must return two fluxes instead of one (one for the flux in the positive direction, one for the flux in the negative direction).
Demo Burgers and file convection_FV__nonlin.hpp.
> feat: Non-conservative fluxes

- include/samurai/field.hpp
- tests/test_field.cpp
`make_field` now accepts an additional parameter (when no initialisation function is given) that is used to fill the newly created field.
It allows to easily create a default initialized field stored in a constant variable. It is related to an issue in `test_field.cpp` where such constant fields were left uninitialised leading to potential test failure.
It is tested in the `copy_from_const` test of `test_field.cpp`.
> feat: additional initial value parameter to make_field 

- demos/FiniteVolume/lid_driven_cavity.cpp
- demos/FiniteVolume/stencil_field.hpp
- demos/FiniteVolume/stokes_2d.cpp
- demos/multigrid/main.cpp
- include/samurai/field.hpp
- include/samurai/graduation.hpp
- include/samurai/mr/mesh.hpp
- include/samurai/petsc/fv/FV_scheme_assembly.hpp
- include/samurai/petsc/fv/cell_based_scheme_assembly.hpp
- include/samurai/petsc/fv/flux_based_scheme_assembly.hpp
- include/samurai/schemes/fv/cell_based/explicit_cell_based_scheme.hpp
- include/samurai/schemes/fv/flux_based/explicit_flux_based_scheme.hpp
- include/samurai/schemes/fv/flux_based/flux_based_scheme__lin_het.hpp
- include/samurai/schemes/fv/flux_based/flux_based_scheme__lin_hom.hpp
- include/samurai/schemes/fv/flux_based/flux_based_scheme__nonlin.hpp
- tests/test_adapt.cpp
- tests/test_periodic.cpp
Trying to fix as many warnings as possible with little change to the code: renaming variable, fixing type alias or adding new one, remove useless cast, ...
Tested with GCC 11.4, 12.3 and LLVM 14.0.
None
Launching the already existing tests.
> fix: fixing (almost) all warnings triggered when compiling tests & demos

- demos/FiniteVolume/AMR_Burgers_Hat.cpp
- demos/FiniteVolume/advection_1d.cpp
- demos/FiniteVolume/advection_2d.cpp
- demos/FiniteVolume/advection_2d_user_bc.cpp
- demos/FiniteVolume/level_set.cpp
- demos/FiniteVolume/level_set_from_scratch.cpp
- demos/FiniteVolume/scalar_burgers_2d.cpp
- demos/FiniteVolume/stencil_field.hpp
- demos/LBM/boundary_conditions.hpp
- demos/tutorial/set_operator.cpp
- include/samurai/algorithm/graduation.hpp
- include/samurai/algorithm/utils.hpp
- include/samurai/mr/criteria.hpp
- include/samurai/mr/operators.hpp
- include/samurai/numeric/prediction.hpp
- include/samurai/numeric/projection.hpp
- include/samurai/operators_base.hpp
- include/samurai/reconstruction.hpp
- include/samurai/stencil_field.hpp
- include/samurai/utils.hpp
`field_operator_base` allows to build operators using the indices `i`, `j`, `k`, ... as in this example
```
template <class TInterval>
class projection_op_ : public field_operator_base<TInterval>
{
public:
INIT_OPERATOR(projection_op_)
template <class T1, class T2>
inline void operator()(Dim<1>, T1& dest, const T2& src) const
{
dest(level, i) = .5 * (src(level + 1, 2 * i) + src(level + 1, 2 * i + 1));
}
}
``` 
The indices are built into the macro `INIT_OPERATOR`. Sometimes, the operator is independent of the dimension and can be written as
```
dest(level, i, index) = ...
```
where `index` is an array where `j`, `k`, ... are stored. To build the array into the macro, we have to give the dimension of the problem. 
This PR adds the dimension as a template argument in the …
> feat: add dim in field_operator_base

- include/samurai/interval.hpp
- tests/test_interval.cpp
Fix the right shift on interval.
When the interval is for example $[-9, 2[$ and we make a right shift, the output can be wrong if we go to 0. The initial interval must always be included in the output interval after the shift.
Before this PR we had
$[-9,  2[ >> 2 = [-3, 0[$
And now
$[-9,  2[ >> 2 = [-3, 1[$
We have added some tests in the `test_interval.cpp` file
- [x ] I agree to follow this project's Code of Conduct
> fix: right shift on interval

- include/samurai/cell.hpp
- include/samurai/cell_array.hpp
- include/samurai/level_cell_array.hpp
- include/samurai/mesh.hpp
- tests/test_cell_array.cpp
This PR gives the possibility to use complex expressions to compute the indices of a point we want to find in a `CellArray`. Instead of using a container, we use a `xexpression` which will be evaluated at the appropriate time.
see test_cell_array.cpp
> feat: use xexpression for get_interval, get_index and get_cell

- include/samurai/interval.hpp
- tests/test_interval.cpp
There was some issues with current implementation of right shift of an `Interval`:
- it was complicated with many checks,
- the result was wrong for right shift of 0 and 2 steps (and probably more).
This PR adds a more thorough test of `Interval`'s left and right shift and implements a new formula for the right shift that is consistent with previous behaviour for unitary step and fixes the others steps.
The formula is explained and justified in the documentation.
Thorough test in `test_interval.cpp`.
> fix: simplifies, fixes and documents left and right shift of Interval

- CMakeLists.txt
- include/samurai/algorithm/update.hpp
- include/samurai/bc.hpp
- include/samurai/field.hpp
- include/samurai/schemes/fv/flux_based/explicit_flux_based_scheme.hpp
Add the compilation variable SAMURAI_CHECK_NAN to initialize fields with NaN and print when a NaN is encountered in the computations.
> feat: check for NaN in the computations

- include/samurai/hdf5.hpp
- [ x] I have installed [pre-commit](https://pre-commit.com/) locally and use it to validate my commits.
- [ x] The PR title follows the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) convention.
- [x ] This new PR is documented.
- [x ] This new PR is tested.
Add precision (float-->double) in XDMF files (see  PR #119  erased by PR #28)
XDMF files read HDF5 files only with single precision while double precision is used for storage.
- [x ] I agree to follow this project's Code of Conduct
> feat: Add precision (float-->double) in XDMF files

- CMakeLists.txt
- include/samurai/algorithm.hpp
- include/samurai/interface.hpp
- include/samurai/schemes/fv/flux_based/explicit_flux_based_scheme.hpp
- include/samurai/schemes/fv/flux_based/flux_based_scheme__nonlin.hpp
OpenMP is used on flux-based schemes. This change is transparent for the user, who must compile samurai with the cmake option WITH_OPENMP=ON.
Any demo with an explicit flux-based scheme.
> feat: OpenMP on fluxes

- include/samurai/bc.hpp
The regions are computed dynamically instead of stored.
> perf: dynamic regions in extrapolation

- include/samurai/schemes/fv/utils.hpp
When no preprocessing variable FLUX_CONTAINER_xxx, use xtensor.
When the CMakeCache is not removed, the new structure was used instead of xtensor, which is supposed to be default value.
> fix: data structure xtensor by default if existing CMakeCache

- include/samurai/schemes/fv/cell_based/cell_based_scheme_definition.hpp
- include/samurai/schemes/fv/utils.hpp
Reintruduce the collapsable std::array that was removed.
Non-linear cell-based schemes didn't compile
> fix: Fix compilation issue on non-linear cell-based scheme

- include/samurai/schemes/fv/operators/diffusion.hpp
Diffusion operator where each field component has its own diffusion coefficient. 
Called with `make_multi_diffusion_order2`.
Tested with the Belousov-Zhabotinski equation.
> feat: Diffusion operator with different coefficient by field component

- include/samurai/interface.hpp
- include/samurai/petsc/fv/flux_based_scheme_assembly.hpp
- include/samurai/schemes/fv/flux_based/flux_based_scheme__lin_het.hpp
- include/samurai/schemes/fv/flux_based/flux_based_scheme__lin_hom.hpp
- include/samurai/schemes/fv/flux_based/flux_based_scheme__nonlin.hpp
Additional `for_each_interface` functions and function renaming.
Breaking change: some `for_each_boundary_interface` functions are renamed into `for_each_boundary_interface__both_directions`. The function with `___` (3 underscores) are renamed with `__` (2 underscores).
> refactor: New for_each_interface functions and function renaming

- demos/FiniteVolume/nagumo.cpp
- include/samurai/algorithm.hpp
- include/samurai/petsc/nonlinear_local_solvers.hpp
- include/samurai/petsc/nonlinear_solver.hpp
- include/samurai/petsc/utils.hpp
OpenMP can be used to parallelize independent, local Newton solvers.
Requires PETSc >= `3.20.6` configured with the option `--with-threadsafety` (which may require `--with-openmp`). Note that the `petsc` conda package is NOT configured with this option.
Samurai must be compiled with the flag `WITH_OPENMP`.
Nagumo demo in 2D with `field_size = 2` and the arguments `--explicit-diffusion --min-level 1 --max-level 4 -omp_num_threads 8`.
On this problem, the achieved speedup is >= 5.
> feat: OpenMP for independent Newton solvers

- include/samurai/interval.hpp
Need to add `fmt::` prefix to function `format_to` for compatibility with C++ 20, since the same function has been added to the stl.
Compilation error in C++ 20.
> fix: add fmt:: prefix to function `format_to`

- demos/FiniteVolume/CMakeLists.txt
- demos/highorder/CMakeLists.txt
- demos/multigrid/CMakeLists.txt
When using `pkg_search_module` to find PETSc, it populates (at least) two variables: `PETSC_LIBRARIES` that contains only the name of the library (ie `petsc`) and `PETSC_LINK_LIBRARIES` that contains the absolute path to the library.
Until this fix, only `PETSC_LIBRARIES` was used that leads to linkage error for some configurations, eg when PETSc is not installed system-wide but only through a package manager like in a conda environment.
Using `PETSC_LINK_LIBRARIES` instead fix this issue.
Compiling and launching affected targets. 
> build: proper link to PETSc library with absolute path

- include/samurai/boundary.hpp
Use `mesh.subdomain()` instead of `mesh.domain()`.
The frontier between subdomains wasn't managed.
Linear convection demo
> fix: Fix flux-based schemes for MPI

- include/samurai/algorithm/update.hpp
When `min_level`is equal to 0, we try to make the intersection with the `level - 1`which is not possible. This PR fixes this issue.
- [ x] I agree to follow this project's Code of Conduct
> fix: keep_only_one_coarse_tag function

- include/samurai/level_cell_array.hpp
When a cell is created from a variadic index in `LevelCellArray`, the type needed by the `Cell`class was not the good one: an `xtensor_fixed` is needed. 
The 3D case of `get_cell` has an issue.
> fix: issue with `get_cell` function in LevelCellArray when `dim > 2`.

- include/samurai/mr/mesh.hpp
It may happen that the neighboring sub-domain adds cells that need to be predicted in the current sub-domain. It turns out that the cells needed for prediction were not created.
This PR corrects this by adding the right cells at the boundaries.
> fix: create missing prediction cells outside the subdomain

- demos/FiniteVolume/manual_block_matrix_assembly.cpp
- include/samurai/petsc/block_assembly.hpp
- include/samurai/petsc/fv/FV_scheme_assembly.hpp
- include/samurai/petsc/fv/flux_based_scheme_assembly.hpp
- include/samurai/petsc/fv/operator_sum_assembly.hpp
- include/samurai/petsc/manual_assembly.hpp
- include/samurai/petsc/matrix_assembly.hpp
- include/samurai/petsc/zero_block_assembly.hpp
Given an `assembly` object,
- Disable the assembly of the boundary fluxes by:
```cpp
assembly.include_boundary_fluxes(false);
```
or
```cpp
assembly.get<0, 0>().include_boundary_fluxes(false);
```
for the (0, 0)-block of a block matrix.
- Set the value that is inserted on the diagonal of useless ghost rows:
```cpp
assembly.set_diag_value_for_useless_ghosts(2);
```
- Iterate on the useless ghost rows:
```cpp
assembly.for_each_useless_ghost_row(
[](auto row)
{
...
});
```
Need to manually compute the boundary fluxes and to access the list of useless ghosts to process other related objects.
`manual_block_matrix_assembly` demo.
> feat: some new capabilities in matrix assembly

- demos/FiniteVolume/manual_block_matrix_assembly.cpp
- include/samurai/algorithm.hpp
- include/samurai/petsc/block_assembly.hpp
- include/samurai/petsc/fv/FV_scheme_assembly.hpp
- include/samurai/petsc/fv/flux_based_scheme_assembly.hpp
- include/samurai/petsc/fv/operator_sum_assembly.hpp
- include/samurai/petsc/manual_assembly.hpp
- include/samurai/petsc/matrix_assembly.hpp
- include/samurai/petsc/zero_block_assembly.hpp
- include/samurai/schemes/fv/utils.hpp
The `Get` enum was moved to `algorithm.h`
Compilation issue where `Get` was not found.
> fix: Fix compilation error on Get

- conda/mpi-environment.yml
- demos/FiniteVolume/manual_block_matrix_assembly.cpp
- include/samurai/interface.hpp
- include/samurai/petsc/block_assembly.hpp
- include/samurai/petsc/fv/FV_scheme_assembly.hpp
- include/samurai/petsc/fv/flux_based_scheme_assembly.hpp
- include/samurai/petsc/zero_block_assembly.hpp
- include/samurai/schemes/block_operator.hpp
- include/samurai/schemes/fv/flux_based/explicit_flux_based_scheme__lin_het.hpp
- include/samurai/schemes/fv/flux_based/explicit_flux_based_scheme__lin_hom.hpp
- include/samurai/schemes/fv/flux_based/explicit_flux_based_scheme__nonlin.hpp
- include/samurai/schemes/fv/flux_based/flux_based_scheme__lin_het.hpp
- include/samurai/schemes/fv/flux_based/flux_based_scheme__lin_hom.hpp
- include/samurai/schemes/fv/flux_based/flux_based_scheme__nonlin.hpp
- Fix the `for_each_boundary_interface()` function with minimal parameters (it wasn't compiling).
- Fix the PETSc insert mode of the projection/prediction coefficients (implicit context).
- The scheme is now copied into the `Assembly` object (instead of storing a reference).
- Possibility to disable the computation of boundary fluxes.
Very quickly.
> fix: Fix some minor issues in the flux-based schemes

- .github/workflows/ci.yml
- conda/environment.yml
- conda/mpi-environment.yml
- include/samurai/hdf5.hpp
- include/samurai/subset/subset_op_base.hpp
This PR updates the functions where fold expressions are used by using `std::apply` or by removing `std::initializer_list` trick.
> refactor: simplify set algebra

- include/samurai/bc.hpp
Enables the definition of boundary regions through cartesian coordinates.
````cpp
auto top_left = samurai::make_bc_region(mesh,
[&](const auto& coord)
{
auto& x = coord(0);
auto& y = coord(1);
return y == 1 && x <= 0;
});
auto top_right = samurai::make_bc_region(mesh,
[&](const auto& coord)
{
auto& x = coord(0);
auto& y = coord(1);
return y == 1 && x > 0;
});
samurai::make_bc<samurai::Neumann<1>>(u, 1.)->on(top_left);
samurai::make_bc<samurai::Neumann<1>>(u, 2.)->on(top_right);
````
> feat: Boundary region with coordinates

- include/samurai/petsc/block_assembly.hpp
- include/samurai/schemes/fv/FV_scheme.hpp
- include/samurai/schemes/fv/cell_based/explicit_cell_based_scheme.hpp
- include/samurai/schemes/fv/explicit_FV_scheme.hpp
- include/samurai/schemes/fv/explicit_operator_sum.hpp
- include/samurai/schemes/fv/flux_based/explicit_flux_based_scheme__lin_het.hpp
- include/samurai/schemes/fv/flux_based/explicit_flux_based_scheme__lin_hom.hpp
- include/samurai/schemes/fv/flux_based/explicit_flux_based_scheme__nonlin.hpp
- include/samurai/schemes/fv/flux_based/flux_based_scheme__lin_het.hpp
- include/samurai/schemes/fv/flux_based/flux_based_scheme__lin_hom.hpp
- include/samurai/schemes/fv/flux_based/flux_based_scheme__nonlin.hpp
- include/samurai/schemes/fv/scheme_operators.hpp
Flux operators are now applicable by direction.
```cpp
auto conv = samurai::make_convection_weno5<...>();
static constexpr std::size_t x = 0;
static constexpr std::size_t y = 1;
unp1 = u - dt*conv(x, u); // applies the scheme in the x-direction only
unp1 = u - dt*conv(y, u); // applies the scheme in the y-direction only
```
> feat: Flux operators applicable by direction

- include/samurai/petsc/fv/FV_scheme_assembly.hpp
The matrix size is set upon calling `assembly.set_unknowns(...)`.
The matrix size was set when the assembly starts. Now it's done sooner.
> fix: The matrix size is set upon calling `assembly.set_unknowns(...)`.

- docs/CODE_OF_CONDUCT.md
- docs/source/reference/bc.rst
- docs/source/reference/finite_volume_schemes.rst
- docs/source/reference/local_schemes.rst
- docs/source/tutorial/graduation_case_1.rst
- docs/source/tutorial/graduation_case_3.rst
- docs/source/tutorial/interval.rst
- docs/source/tutorial/level_set.rst
- docs/source/tutorial/operator_on_subset.rst
I have used codespell to find typos and fixed them by hand.
> docs: fix some typos in docs

- docs/environment.yml
- include/samurai/algorithm/update.hpp
- include/samurai/bc.hpp
Improvements mainly on uniform meshes.
Heat demo, level 6: update_ghost_mr() executes over 60% faster.
> perf: `update_ghost_mr()` performance improved on uniform meshes

- include/samurai/petsc/fv/FV_scheme_assembly.hpp
- include/samurai/petsc/fv/operator_sum_assembly.hpp
- include/samurai/schemes/fv/scheme_operators.hpp
For a sum of scheme, the one with largest stencil now assembles the BC into the matrix. If all schemes in the sum are local, no BC is required anymore.
Upon assembling the matrix of a local scheme (1-cell stencil), an error was raised saying that the field had no BC.
> fix: BC no longer required to assemble the matrix of a local scheme

- .github/workflows/ci.yml
- include/samurai/bc.hpp
Fill external corners by polynomial extrapolation even on uniform meshes. 
This fixes a regression introduced in #230.
Some schemes have box stencils along with boundary conditions that only fill ghosts in Cartesian direction. Therefore, the corner ghosts are used by the scheme without being filled by the user code.
> fix: fill corners on uniform meshes

- demos/FiniteVolume/lid_driven_cavity.cpp
- demos/FiniteVolume/stokes_2d.cpp
- include/samurai/petsc/block_assembly.hpp
- include/samurai/petsc/linear_block_solver.hpp
- include/samurai/petsc/linear_solver.hpp
The fieldsplit PC can be used with a monolithic matrix.
Stokes demo.
> feat: fieldsplit PC for monolithic matrix

- include/samurai/mr/adapt.hpp
fix enlarge naming. We used the same name for the template variable and the function, which is not possible. 
> fix: enlarge

- include/samurai/mesh.hpp
The number of cells for a given mesh is computed using the sum of the size of each interval in x-direction. However, if we want to compute the maximum number of cells (which is used when we resize a field), we can do this much faster using the last x-interval:
- The start of the interval + the offset gives the memory location of the cell for that start.
- If we add the size of the interval, we get the maximum number of cells.
> perf: Improve nb cells

- include/samurai/mesh.hpp
- include/samurai/subset/subset_node.hpp
- include/samurai/subset/subset_op_base.hpp
- include/samurai/uniform_mesh.hpp
This PR removes the computation of the index of each interval found in the algebra of set. This index is only used during the renumbering phase of the sub meshes. We improve the performance of the renumbering by removing the old implementation.
> perf: remove apply interval index

- include/samurai/field.hpp
Update calls to `get_interval` by removing hardcoded "READ" and  "WRITE" strings.
> perf: remove hardcoded access modes in get_interval

- include/samurai/level_cell_array.hpp
Some views/ranges are replaced with explicit loops.
> perf: replace views/ranges with loops

- include/samurai/mr/operators.hpp
- include/samurai/static_algorithm.hpp
Fix prediction of order 0.
Compilation either raising a recursive error, or taking too much memory before being killed by the OS.
In linear convection demo:
```cpp
samurai::MRConfig<dim, 3, 3, 0>;
```
> fix: Fix prediction order 0

- include/samurai/mr/adapt.hpp
If the gradation is greater than one, we need to look at the intersections between two levels by translating one of them by one at each time until to reach the graduation width.
Before this PR, we made the translation of a graduation width which means that we can move too fast.
> fix: the tagged cells with the graduation

- include/samurai/bc.hpp
- tests/test_adapt.cpp
The set algebra of the BC had a bug. An intersection with `mesh_id_t::reference` was missing to ensure that the resulting set returned actual cells/ghosts. The bug occurred on the levels lower than the min_level.
> fix: fix BC

- include/samurai/storage/containers_config.hpp
In structure `Array`, the template parameter `SOA` is defaulted to `false`.
It broke some user codes.
> fix: default value for SOA in Array

- include/samurai/field.hpp
Replace `interval_t::index_t` with `interval_t::value_t` in `field(level, i, index)` (for scalar fields).
> fix: Fix type issue in Field.operator()

- include/samurai/algorithm.hpp
- include/samurai/level_cell_array.hpp
- include/samurai/mesh.hpp
- tests/CMakeLists.txt
- tests/test_find.cpp
The new function returns the cell that contains the given cartesian coordinates:
```cpp
auto cell = samurai::find_cell(mesh, {0.4, 0.8});
```
> feat: find cell from cartesian coordinates

- include/samurai/bc.hpp
- include/samurai/boundary.hpp
- include/samurai/interface.hpp
- include/samurai/mesh_interval.hpp
- include/samurai/petsc/block_assembly.hpp
- include/samurai/petsc/fv/FV_scheme_assembly.hpp
- include/samurai/petsc/fv/operator_sum_assembly.hpp
- include/samurai/petsc/linear_block_solver.hpp
- include/samurai/petsc/linear_solver.hpp
- include/samurai/petsc/matrix_assembly.hpp
- include/samurai/petsc/nonlinear_solver.hpp
- include/samurai/petsc/solver_helpers.hpp
- include/samurai/schemes/block_operator.hpp
- include/samurai/schemes/explicit_scheme.hpp
- include/samurai/schemes/fv/FV_scheme.hpp
- include/samurai/schemes/fv/cell_based/cell_based_scheme_definition.hpp
- include/samurai/schemes/fv/cell_based/explicit_cell_based_scheme.hpp
- include/samurai/schemes/fv/explicit_FV_scheme.hpp
- include/samurai/schemes/fv/explicit_operator_sum.hpp
- include/samurai/schemes/fv/flux_based/explicit_flux_based_scheme__lin_het.hpp
- include/samurai/schemes/fv/flux_based/explicit_flux_based_scheme__lin_hom.hpp
- include/samurai/schemes/fv/flux_based/explicit_flux_based_scheme__nonlin.hpp
- include/samurai/schemes/fv/flux_based/flux_definition.hpp
- include/samurai/schemes/fv/scheme_operators.hpp
- include/samurai/static_algorithm.hpp
- include/samurai/stencil.hpp
- include/samurai/storage/containers_config.hpp
- include/samurai/timers.hpp
- A `StencilAnalyzer` class has been added to gather information about the stencil. This way, the analysis of the stencil is done only once instead of at every interval, thus improving the performance of the `StencilIterator`.
- The scheme object is no longer `const`, so that temporary variables can be stored in the class and reused upon application of the scheme. This change prepares the possibility of applying a scheme by batches.
> refactor: improve `StencilIterator` and the schemes are not `const` anymore

- include/samurai/arguments.hpp
- include/samurai/boundary.hpp
- include/samurai/mr/adapt.hpp
- include/samurai/schemes/fv/flux_based/flux_based_scheme.hpp
- include/samurai/schemes/fv/flux_based/flux_based_scheme__nonlin.hpp
Use the command line argument `--refine-boundary` to keep a layer of boundary cells refined at max_level. The layer width corresponds to `Mesh::config::max_stencil_width`, in order to make sure that no interior interface computes its flux with a stencil that is partially outside of the domain. That way, only boundary interfaces use outside ghosts.
Although this refinement is artificial, it solves two problems (until we can find proper solutions):
- Numerous bugs occur when a stencil around an interior interface is partially outside the domain. In that case, it is not clear how many ghosts must be created and how to fill them.
Typical bad situation:
```
domain           |     outside
|
|====|====|----|----|----|----|                                
|
| …
```
> feat: Refine boundary

- demos/FiniteVolume/CMakeLists.txt
From the **Issue** https://github.com/hpc-maths/samurai/issues/271#issue-2868526250, the user cannot compile from source a test case using PETSc headers.
I fix this by editing the associated CMakeLists.txt file
- Previously, CMake failed to locate the PETSc headers
- Added include_directories to resolve this
- Now it works correclty (verified with Spack PM)
Now, PETSc header is correctly found and the test case compiles successfully.
https://github.com/hpc-maths/samurai/issues/271
> build: PETSc headers

- demos/FiniteVolume/CMakeLists.txt
- demos/highorder/CMakeLists.txt
- demos/multigrid/CMakeLists.txt
- PETSC headers :
-	Previously, petsc headers are not included in multigrid, highorder and one FiniteVolume Demo.
-	Without conda-forge, we need to add it manually
- CLI11 linking :
-	Previously, CLI11 was not included in the link
> build: cmake correction

- include/samurai/mesh.hpp
- We send the mesh to the neighborhood with `boost::send` calls
- But currently, this `boost::send` serialize the mesh for **each** send, even if it is always the same mesh.
- But we can serialize the mesh once and send the buffer.
- It is only tested on advection-2d, with a performance gain
Performance issue when using MPI
It has been tested on the advection-2d test case
> perf: Avoid multiple serialization

- include/samurai/mesh.hpp
- Previously, in multirank MPI, m_cells was empty due to a bad n_cells per subdomains computation
- Then I add a specific partitioning for 1D MPI :
- We compute the number of cells in the original mesh
- Each subdomain gets a part of the nb_cells
Previously, in 1D, in multirank MPI, the mesh was constructed empty. 
see https://github.com/hpc-maths/samurai/issues/290#issue-2928445322
advection_1d is runnin, butt we need more tests
> fix: Repare MPI in 1D

- include/samurai/schemes/fv/flux_based/flux_based_scheme__nonlin.hpp
When `prediction_order = 0`, the computation of fluxes at the finest level failed.
Tested on two-scale-capillarity code.
> fix: Fix `enable_max_level_flux` for prediction 0

- include/samurai/petsc/utils.hpp
Functions have been added to copy an xtensor into a petsc Vec and vice versa.
Needed by Libertas
Libertas code.
> feat: add copy functions xtensor <-> Petsc Vec

- include/samurai/level_cell_array.hpp
- tests/CMakeLists.txt
- tests/test_domain_with_hole.cpp
An origin point can be passed to a LevelCellArray so that two LCA can interact even if they are built from different boxes.
`test_domain_with_hole.cpp`
> feat: LevelCellArray with origin point

- include/samurai/algorithm.hpp
- include/samurai/field.hpp
- include/samurai/mesh.hpp
- include/samurai/mr/mesh.hpp
**This PR should be verified, do not merge without validation**
In MPI, we send unnecessary mesh_id_ts.
This PR just avoid these sends.
It enables in some cases a gain of around 10% in comparison with the current PR.
This PR do not reconstruct the local mesh. This has to be done in another PR. 
- There are some locations that continues to use `update_neighbour_mesh` at the `Mesh_base` constructor , I may have to replace them
- I suggest (Not in this PR) to rename `update_mesh_neighbour` by `update_neighbour_mesh`, or `update_neighbour_meshid` by `update_meshid_neighbour` but it seems to be less clear for me. 
- I may factorize `update_meshid` and `update_subdomain` to send arbitrarily a n `m_cells[id]` or a `m_subdomain`. The code could be unclear 
Available tags: 'build', 'chore', 'ci', …
> perf: Avoid useless MPI send

- include/samurai/mesh.hpp
Previously, due to a `int` versus `std::size_t` comparison, there was a warning. 
This PR cast the int and remove the warning. 
```warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::size_t’ {aka ‘long unsigned int’} [-Wsign-compare]```
advection-2d
> fix: remove warning

- include/samurai/mesh.hpp
Here is a naive solution to construct in a naive way the neighbourhood. 
It is optimal as long as you are using a naive partition as for now. 
Each rank have one or two neighbours. 
This do not works properly with periodic.
We need to improve this implementation by adding new `find_neighbourhood_<strategy>` in the future. 
Perforance issue
on advection-2d
> perf: Naive neighbourhood

- include/samurai/static_algorithm.hpp
Some functions declared in `static_algorithm.hpp` use `LevelCellArray`.
Therefore, including `static_alogrithm.hpp` in the "wrong order" (i.e. before `LevelCellArray` is declared) will produce an error.
This issue can be resolved by forward declaring `LevelCellArray`. 
> fix: forward declare LevelCellArray in static_algorithm.hpp

- include/samurai/timers.hpp
Previously, the average timer was buggy and displayed the rank-0 time. This commit corrected that and computed the actual average value.
Average timer was incorrect.
In `advection-2d` with 3 ranks.
> fix: correct timer

- include/samurai/io/restart.hpp
- include/samurai/io/util.hpp
- include/samurai/mesh.hpp
- include/samurai/mr/mesh.hpp
This PR allows a parallel simulation to be restarted. Since load balancing has not yet been completed, the restart process checks that the number of processes is the same in the simulation that is being restarted and in the restart file. If not, an error message is displayed.
This constraint will be removed once load balancing is working as expected.
> feat: parallel restart

- include/samurai/storage/collapsable_linear_algebra.hpp
* Add the boolean template parameter `can_collapse` to all `mat_vec` functions.
* Correct function deduction of `mat_vec` when use implicit scheme
> fix: fix template deduction for mat_vec function

- .github/workflows/ci.yml
- include/samurai/algorithm/graduation.hpp
The graduation didn't work well with periodic conditions. This PR fixes this issue by applying the same algorithm to the inside cells and the periodic cells. For periodic conditions, we duplicate the mesh in all directions where this condition has to be applied.
> fix: graduation when periodic conditions are used

- demos/FiniteVolume/burgers_mra.cpp
- include/samurai/arguments.hpp
- include/samurai/reconstruction.hpp
- include/samurai/schemes/fv/flux_based/explicit_flux_based_scheme__nonlin.hpp
- include/samurai/schemes/fv/flux_based/flux_based_scheme.hpp
- include/samurai/schemes/fv/flux_based/flux_based_scheme__nonlin.hpp
- tests/test_portion.cpp
This PR removes the option `--enable--max-level-flux` and replaces it with the more flexible option `--finer-level-flux`. Setting this option to `-1` results in the same behaviour as before with  the option `--enable--max-level-flux`. If a positive integer `i` is provided, the flux is computed at `level + i`.
> feat: add finer-level-flux option

- include/samurai/algorithm/update.hpp
When a user adds its own prediction function that updates the values in the refine cells, this function is not used by the extra fields in the MRA adaptation. This PR fixes this issue.
> fix: user prediction function

- demos/FiniteVolume/burgers.cpp
- demos/FiniteVolume/burgers_mra.cpp
- demos/FiniteVolume/burgers_os.cpp
- demos/FiniteVolume/heat.cpp
- demos/FiniteVolume/heat_heterogeneous.cpp
- demos/FiniteVolume/heat_nonlinear.cpp
- demos/FiniteVolume/lid_driven_cavity.cpp
- demos/FiniteVolume/linear_convection.cpp
- demos/FiniteVolume/linear_convection_obstacle.cpp
- demos/FiniteVolume/nagumo.cpp
- demos/FiniteVolume/stokes_2d.cpp
- demos/highorder/main.cpp
- demos/tutorial/reconstruction_2d.cpp
- docs/source/reference/finite_volume_schemes.rst
- docs/source/reference/local_schemes.rst
- include/samurai/algorithm/update.hpp
- include/samurai/field.hpp
- include/samurai/reconstruction.hpp
- include/samurai/schemes/fv/FV_scheme.hpp
- include/samurai/schemes/fv/cell_based/cell_based_scheme_definition.hpp
`update_ghost_mr(u);` is called internally when needed:
- in flux-based and cell-based schemes (e.g. `conv(u)`)
- in `reconstruction(u)`
- in `transfer(u, v)`
In order not to perform the ghost update multiple times, the field stores boolean `ghost_updated` flag, which is set to true when `update_ghost_mr(u)` is called, and set to false when `u` is modified by samurai (but not when `u` is directly modified by the user, e.g. in a `for_each_cell` call). Consequently, existing codes will work without loss of performance.
> feat: automatic update_ghost_mr()
